### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [Oldes/Sublime-Rebol#2]
We would like to use your lexer at github/linguist to highlight REBOL code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@Oldes Did you get a chance to look into this?

**Comment by pchaigno** [comment]
@Oldes Any update? We would really like to use this lexer but can't without a license :yellow_heart:

**Comment by Oldes** [comment]
Sorry, I missed this issue:) Is it correct now? https://github.com/Oldes/Sublime-REBOL/commit/102402f71aa3a7770b0c06c0183eff1be78e7280

**Comment by Oldes** [comment]
I've also modified this in linguist: https://github.com/github/linguist/pull/2257

**Comment by pchaigno** [comment]
> Sorry, I missed this issue:) Is it correct now? 102402f

Should be okay. Thanks!
